version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: finanzas_db
    restart: always
    environment:
      POSTGRES_DB: finanzas_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
