spring:
  application:
    name: finanzas

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finanzas_db}
    username: ${DB_USER:dev_user}
    password: ${DB_PASS:dev_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:41e942c1369361b4160fccd01bd015591c2b66e5f26273c098587e401e321ef1}
  expiration: 86400000

springdoc:
  api-docs:
    path: /v1/api-docs
    enabled: true