spring:
application:
name: auth-service

datasource:
url: jdbc:postgresql://localhost:5432/auth_db
username: auth_user
password: password123
driver-class-name: org.postgresql.Driver

jpa:
database-platform: org.hibernate.dialect.PostgreSQLDialect
hibernate:
ddl-auto: update  # Para desarrollo, que cree las tablas automáticamente
show-sql: true

kafka:
bootstrap-servers: localhost:9092
producer:
key-serializer: org.apache.kafka.common.serialization.StringSerializer
value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
secret: 41e942c1369361b4160fccd01bd015591c2b66e5f26273c098587e401e321ef1
expiration: 86400000

springdoc:
swagger-ui:
path: /auth/swagger-ui.html
api-docs:
path: /auth/v3/api-docs
version: openapi_3_1
# Eureka

eureka:
instance:
instance-id: ${spring.application.name}:${random.value}
prefer-ip-address: true
client:
service-url:
defaultZone: http://localhost:8761/eureka/
server:
port: 0